config/routes.rb
Invitask::Application.routes.draw do
  
  get "index/index"

  devise_for :users, :controllers => { 
    :registrations => "users/registrations",
  }

  devise_scope :user do
    match '/invitation/:token' => 'users/registrations#new'
  end

  resources :invitations do 
    member do 
      post :resend
    end
  end

  root :to => 'index#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  attr_accessible :token, :email, :accepted

  validates_formatting_of :email, :using => :email
  validates_uniqueness_of :email, :token
  validates_presence_of :email, :token

  after_save do 
    if self.new_record? || self.token_changed? || self.email_changed?
      self.send_invitations
    end    
  end

  def token_url
    "http://#{configatron.host}/invitation/#{self.token}"
  end

  def send_invitations
    UserMailer.invitation_instructions(self).deliver
  end

  def self.get_random_token
    Devise.friendly_token[0,20]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :phone, :email, :password, :password_confirmation, :remember_me, :token
  attr_accessor :token

  validate :token, :validate_token
  validates_presence_of :name
  validates_formatting_of :email, :using => :email  
  validates_format_of :phone, 
    :allow_blank => true,
    :message => "must be a valid telephone number.",
    :with => /^[\(\)0-9\- \+\.]{10,20} *[extension\.]{0,9} *[0-9]{0,5}$/i 

  after_create do 
    invitation = Invitation.where(:token => self.token).first
    if invitation
      invitation.accepted = true
      invitation.save
    end
  end

  protected

  def validate_token
    if self.new_record? && self.token != nil # allow create accout with no token
      if self.token == ""
        self.errors.add(:base, "Invitation is required")
      else
        invitation = Invitation.where(:token => self.token).first
        if invitation == nil
          self.errors.add(:base, "Invitation token is invalid")
        elsif invitation.accepted
          self.errors.add(:base, "Invitation token already accepted")
        end
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
    @invitations = Invitation.all
  end

  def show
    @invitation = Invitation.find(params[:id])
  end

  def new
    @invitation = Invitation.new
    @invitation.token = Invitation.get_random_token
  end

  def create
    @invitation = Invitation.new(params[:invitation])
    if @invitation.save
      redirect_to @invitation, :notice => "Successfully send invitation."
    else
      render :action => 'new'
    end
  end

  def edit
    @invitation = Invitation.find(params[:id])
  end

  def update
    @invitation = Invitation.find(params[:id])
    if @invitation.update_attributes(params[:invitation])
      redirect_to @invitation, :notice  => "Successfully resend invitation."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy
    redirect_to invitations_url, :notice => "Successfully destroyed invitation."
  end

  def resend
    invitation = Invitation.find(params[:id])
    invitation.send_invitations
    redirect_to invitations_url, :notice => "Successfully resend invitation to #{invitation.email}."
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  def new
    @invitation = Invitation.where(:token => params[:token]).first
    super
  end

  def create
    build_resource
    resource.token = params[:token].to_s
    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      respond_with resource
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper

  def invitation_url(inviation)
    "#{request.fullpath}"
  end
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/index/index.html.erb
<h1>Index#index</h1>
<p>Find me in app/views/index/index.html.erb</p>

app/views/invitations/_form.html.erb
<%= form_for @invitation do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/invitations/edit.html.erb
<% title "Edit Invitation" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @invitation %> |
  <%= link_to "View All", invitations_path %>
</p>

app/views/invitations/index.html.erb
<% title "Invitations" %>

<table>
  <tr>
    <th>Token</th>
    <th>Email</th>
    <th>Accepted</th>
    <th colspan="3">Actions</th>
  </tr>
  <% for invitation in @invitations %>
    <tr>
      <td><%= invitation.token %></td>
      <td><%= invitation.email %></td>
      <td><%= invitation.accepted %></td>
      <td><%= link_to "Show", invitation %></td>
      <% unless invitation.accepted %>
        <td><%= link_to "Resend", resend_invitation_path(invitation), :method => :post %></td>
        <td><%= link_to "Edit", edit_invitation_path(invitation) %></td>
        <td><%= link_to "Destroy", invitation, :confirm => 'Are you sure?', :method => :delete %></td>
      <% else %>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      <% end %>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Invitation", new_invitation_path %></p>

app/views/invitations/new.html.erb
<% title "New Invitation" %>

<%= render 'form' %>

<p><%= link_to "Back to List", invitations_path %></p>

app/views/invitations/show.html.erb
<% title "Invitation" %>

<p>
  <strong>Token:</strong>
  <%= @invitation.token %>
</p>
<p>
  <strong>Email:</strong>
  <%= @invitation.email %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @invitation.accepted %>
</p>

<p>
  <%= link_to "Edit", edit_invitation_path(@invitation) %> |
  <%= link_to "Destroy", @invitation, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", invitations_path %>
</p>

app/views/layouts/_suggest_for_input_registration_fields.html.erb
<p style="width:100%;text-align:center">
  <%= link_to "What about your phone?", edit_user_registration_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <% if current_user && !current_user.phone %>
      <%= render "layouts/suggest_for_input_registration_fields" %>
    <% end %>
    <ul>
      <li>
        <%= link_to "index.php", root_path %>
      <li>
        <%= link_to "Invitations", invitations_path %>
      <% unless current_user %>
        <li>
          <%= link_to "Sign In", new_user_session_path %>
      <% else %>
        <li>
          <%= link_to "My Profile", edit_user_registration_path %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

      <% end %>
    </ul>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>